import { ResponsiveTreeMap } from "@nivo/treemap";
import { Box } from "@mui/material";

const rawData = {
  Veterinarians: 1,
  Sports: 5,
  "Carpet Cleaner": 1,
  "Retirement Community.": 2,
  ATV: 2,
  Accountants: 20,
  "Spark Plugs": 1,
  Windows: 7,
  "Meal Plan": 1,
  "Office Products": 10,
  Tires: 22,
  Cybersecurity: 1,
  Wallpaper: 1,
  Lawnmower: 1,
  Paint: 7,
  Snacks: 24,
  "Continuing Medical Education.": 1,
  Printer: 3,
  Napkins: 1,
  Motorcycles: 8,
  Glue: 4,
  Soap: 5,
  Mat: 1,
  "Electronic Health Records": 4,
  "Automotive/Industrial": 2,
  eggs: 1,
  Fan: 1,
  Petmed: 3,
  "Health System": 2,
  Suncreen: 3,
  "U.S. Military": 7,
  Coffeemaker: 2,
  Electronics: 10,
  Recruiters: 10,
  Safe: 1,
  Lotion: 2,
  Sunglasses: 1,
  "Weight Loss Program": 1,
  Hospice: 1,
  Aerospace: 7,
  Dishwashing: 1,
  Stores: 143,
  "Golf Resort": 5,
  Seasonings: 1,
  "Building Supplies": 2,
  Primer: 1,
  Magazine: 191,
  Engravers: 1,
  Restaurant: 25,
  "Gas Grill": 1,
  "Fishing Line": 1,
  Wheels: 3,
  "Audio-Visual Equipment & Supplies": 2,
  "Transportation Company": 2,
  Salt: 2,
  Hotel: 160,
  Travel: 9,
  Cookware: 3,
  Copier: 1,
  "Dental Products": 3,
  Software: 2,
  Bicycle: 3,
  Fertilizer: 2,
  "Theme Park": 1,
  Cereals: 30,
  "Educational Material": 1,
  Beverage: 54,
  "Insurance Cos.": 156,
  "Mortgage Company": 1,
  Thickener: 1,
  "University/College": 10,
  Broker: 1,
  "FINANCIAL SERVICES": 4,
  Physicians: 69,
  Disinfectant: 2,
  "Personal Locator Beacon": 1,
  Firelog: 1,
  Brick: 1,
  "Blade Razor": 2,
  "Dentists/Physicians": 2,
  Belt: 1,
  "Oil Company": 10,
  "Chewing Gum": 1,
  Matchmaker: 4,
  Bathtub: 1,
  Tape: 3,
  "Raisin Bran": 1,
  "Post Office": 9,
  "Investment Firms": 189,
  "MEDIA & PUBLISHING": 1,
  Tissue: 5,
  Airplane: 10,
  Stoves: 2,
  "Prescription Pad": 1,
  Outboards: 3,
  Tea: 14,
  Flowers: 2,
  Sauce: 4,
  "Fabric Softener": 1,
  "Pet Food": 93,
  "Multi-Specialty Group": 3,
  School: 1,
  "Publishers.": 4,
  Bandage: 1,
  "Real Estate Cos.": 55,
  "Financial Advisers": 1,
  Tractor: 1,
  Alarm: 2,
  Plants: 1,
  "Medical Procedure": 5,
  "Weed Preventer": 1,
  "Air Cargo& Package Express Service": 1,
  "Shampoo.\nShampoo.": 33,
  "Audio Visual": 5,
  Tiles: 13,
  Mayonnaise: 7,
  "Smoke Detector": 1,
  Newspaper: 19,
  "Paper Plate": 1,
  Library: 1,
  "Bathroom Scale": 1,
  "Pharmaceutical Cos.": 120,
  "Medical Products": 50,
  Flour: 1,
  "Garage Door": 1,
  Books: 12,
  "Dietary supplement": 1,
  Cheese: 6,
  Automotive: 20,
  "Healthcare Company": 2,
  "Baby Products": 1,
  "Kitchen & Bath Fixtures": 1,
  Blinds: 1,
  "College/University": 95,
  "Motor Oil": 5,
  Tortillas: 1,
  "Industrial Gas": 1,
  "Cooking Oil": 5,
  Socks: 7,
  Headphones: 10,
  Builder: 4,
  Goggle: 1,
  "Limousine Service": 1,
  Furniture: 17,
  "Medical Device": 54,
  "Pet Product": 15,
  "Radar Detector": 1,
  Toothpaste: 20,
  "Body Liner": 1,
  Entertainment: 13,
  Dressing: 7,
  "Toilet Paper": 2,
  Drugs: 890,
  "Air Freshener": 1,
  Butter: 6,
  "Travel Agency": 24,
  "Peanut Butter": 2,
  Sweetener: 2,
  "Noise-Cancelling Headphones": 1,
  Filter: 2,
  Deodorant: 1,
  Batteries: 12,
  Tampons: 4,
  "Computers & Office": 41,
  "Ice Cream": 5,
  Appliances: 34,
  Cream: 10,
  "Medical Technological Co.": 2,
  Television: 8,
  Pharmacy: 1,
  Toothbrush: 5,
  Creamers: 2,
  Lenses: 15,
  Coffee: 34,
  "Medical School": 1,
  "Body Lotion": 1,
  "Skin Care Products": 1,
  "OFFICE SUPPLIES": 19,
  Movers: 2,
  Water: 2,
  Cosmetics: 121,
  "Home Entertainment": 1,
  Dealer: 1,
  "Medical Organization": 34,
  Banks: 144,
  Pies: 1,
  "Strategy & Technology Consultants": 1,
  "Air Conditioner": 6,
  Camera: 12,
  "Home Health Agency": 1,
  "City/State/Country": 472,
  Gardening: 1,
  Film: 6,
  Vinaigrettes: 1,
  Gifts: 1,
  Pads: 8,
  Website: 1,
  Glasses: 1,
  Cabinetry: 1,
  Footbed: 1,
  Glove: 2,
  Cleaner: 1,
  Towels: 2,
  Pen: 15,
  Flooring: 2,
  Registry: 1,
  "Auto Accessories": 6,
  "Tools & Home Improvement": 5,
  Food: 270,
  Clubs: 1,
  "Medical Device Co.": 12,
  Sonar: 1,
  "Canned Fruit": 1,
  Lockset: 1,
  Suitcase: 20,
  Tents: 1,
  Tourism: 1,
  TELECOMS: 2,
  Attorneys: 9,
  Pepper: 1,
  "Swimming Pool": 1,
  "Federal Agency": 2,
  "Orange Juice": 1,
  Cleanser: 1,
  Condominium: 1,
  Airport: 12,
  "Health Information System": 1,
  Realtor: 3,
  "Hair Theerapy": 1,
  Rifles: 1,
  Supplement: 14,
  Shaver: 2,
  "Cream Cheese": 2,
  Museum: 2,
  "Contact Lenses": 2,
  Automobiles: 348,
  "Consulting Firm": 3,
  "Travel Management Co.": 2,
  Hospitals: 242,
  Airlines: 168,
  Aquarium: 1,
  Radiology: 3,
  Carpet: 7,
  Loudspeakers: 1,
  Soles: 1,
  "Aviation Company": 1,
  Massager: 1,
  "TRANSPORT & TRAVEL": 1,
  Vitamins: 4,
  Cookies: 5,
  Clothing: 63,
  "Insect Killer": 1,
  Bed: 14,
  //"[no category]": 15126,
  "International Organization": 1,
  "Photo Archives": 1,
  Bookstore: 2,
  Knife: 2,
  Milk: 18,
  "Shopping Mall": 2,
  Oatmeal: 2,
  "Handheld Devices": 1,
  Detergent: 18,
  Projector: 1,
  Mattress: 3,
  Rice: 1,
  Conditioner: 1,
  Shoes: 67,
  Fragrance: 33,
  "Telecommunications Company": 39,
  "Exercise Equipment": 3,
  Fruit: 2,
  Potatoes: 1,
  "Wood Floor Cleaner": 1,
  Margarine: 3,
  Grill: 1,
  Sofa: 1,
  Boats: 12,
  "Shoes\nShoes": 1,
  Jewelry: 173,
  Sugar: 5,
  "Golf Products": 22,
  Chocolate: 37,
  Roller: 1,
  Faucet: 5,
  "Olive Oil": 5,
  Powder: 1,
  "Credit Card Company": 67,
  "Car Rental Company": 29,
  "HEALTH & BEAUTY": 24,
  Caramel: 1,
  Adhesive: 3,
  Refrigerator: 1,
  Education: 1,
  "Dishwashing Liquid": 4,
};

var colorIncrement = 30;
var timesCalled = 0;
function gimmeAColor() {
  const color = (colorIncrement * timesCalled) % 360;
  timesCalled += 30;
  return color;
}

function toNivoData(d) {
  const children = [];
  Object.entries(d).forEach(([category, count]) => {
    children.push({
      name: category,
      color: `hsl(${gimmeAColor()}, 70%, 50%)`,
      loc: count,
    });
  });

  return {
    name: "categories",
    color: "hsl(173, 70%, 50%)",
    children: children.sort((a, b) => b["loc"] - a["loc"]),
  };
}

export default function Dashboard() {
  return (
    <Box
      sx={{
        height: 750,
        width: "100%",
        "& .actions": {
          color: "secondary",
        },
        "& .textPrimary": {
          color: "primary",
        },
      }}
    >
      <ResponsiveTreeMap
        data={toNivoData(rawData)}
        identity="name"
        value="loc"
        valueFormat=".02s"
        margin={{ top: 10, right: 10, bottom: 10, left: 10 }}
        labelSkipSize={12}
        labelTextColor={{
          from: "color",
          modifiers: [["darker", 1.2]],
        }}
        parentLabelPosition="left"
        parentLabelTextColor={{
          from: "color",
          modifiers: [["darker", 2]],
        }}
        borderColor={{
          from: "color",
          modifiers: [["darker", 0.1]],
        }}
      />
    </Box>
  );
}
